Server, Executor: Fixed bugs and modified unit tests (#14)
* 修改parser引用，更改为DCParser

Signed-off-by: Orion7r <50295175+Orion7r@users.noreply.github.com>

* 修改LEARNING_GUIDANCE.zh.md

Signed-off-by: Orion7r <50295175+Orion7r@users.noreply.github.com>

* 修改br引用，将其更改为 dcbr

Signed-off-by: Orion7r <50295175+Orion7r@users.noreply.github.com>

* fix bug：result format is invalid parameter in pgsql extended query bind message

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* Fixed Typo around ReadyForQuery

Signed-off-by: David <davidyangad@gmail.com>

* Added Error handling for undefined table (MySQL code 1051)

Signed-off-by: David <davidyangad@gmail.com>

* fix pgsql data type mapping

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* cleanup handle_error.go

Signed-off-by: David <davidyangad@gmail.com>

* fix data type mapping

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* fixed typo for ReadForQuery

* Added handler for Undefined table error

* fixed a problem where trying to convert uint32 to string causes compilation error

* delete invalid code

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* added unit test for parseHandshake and malformedInitialMessage

* Added unit test for receive SSL request

* added unit test for write back authentication ok

* executor: fix param maker sortor

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* added unit test for dispatch simple query, make tidb return EOF when client quit

* fixed unit test for conn execution timeout

* executor: fix user password encryption unit test in simple_test

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* Improve the initial data for information_schema

Fixed some unit test bugs

Signed-off-by: Orion7r <50295175+Orion7r@users.noreply.github.com>

* show_stats_test.go : update unit test

* executor: fix prepare stmt unit test

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* delete private doc

Signed-off-by: jk <51103574+pupillord@users.noreply.github.com>

* typo fix and added basic structure for handle error tests

* added unit test for handleUndefinedTable function in server/handle_error

* added unit test for handleInvalidGroupFuncUse, fixed a small bug in calculating position field of error message

* added unit test for handleFieldSpecifiedTwice

* restructured handle_error_test and removed unnecessary sql executions

* removed handleTypeError since its being triggered by other errors sharing the error code 1105

* added sql set up and triggering for all error conversion methods

* added captured error response from psql to unit test

* bug fix: handleCantDropFieldOrKey returned wrong error code and has OBOB in table name calculation

* changed unit test structure for more readble test result

* added hint for handleDerivedMustHaveAlias, now its unit test will pass

* fixed bug in handleMultiplePKDefined where incorrect table name calculation is causing panic

* added test option struct to control what to test

* fixed TestWrongNumberOfColsInSelect

* fixed TestHandleDataTooLong, it no longer tries to compare error message

* fixed TestHandleDuplicateKey so it no longer compares message or detail

* fixed TestHandleNoDefaultValue so it no longer compares detail

* fixed TestHandleDataOutOfRange so it no longer compares message

* fixed TestHandleColumnMismatch so it no longer compares position

* removed unit test for handleSubqueryNo1Row as it's returning incompatible error format

Co-authored-by: Orion7r <50295175+Orion7r@users.noreply.github.com>
Co-authored-by: jk <jiangkunf@digitalchina.com>
Co-authored-by: jk <51103574+pupillord@users.noreply.github.com>